#include <bits/stdc++.h>
using namespace std;
struct BitWriter{ vector<unsigned char> o; unsigned cur=0,n=0; void bit(int b){cur=(cur<<1)|(b&1); if(++n==8){o.push_back(cur);cur=n=0;}} void finish(){if(n){cur<<=(8-n);o.push_back(cur);cur=n=0;}}};
struct BitReader{ const vector<unsigned char>& a; size_t p=0; int n=0; unsigned cur=0; BitReader(const vector<unsigned char>&x):a(x){} int bit(){if(!n){cur=p<a.size()?a[p++]:0;n=8;} int b=(cur>>7)&1;cur<<=1;--n;return b;}};
struct AE{uint64_t lo=0,hi=0xffffffffULL; unsigned pending=0; BitWriter w;void out(int b){w.bit(b); while(pending){w.bit(!b);--pending;}}void enc(int sym,uint32_t c0,uint32_t c1){uint64_t r=hi-lo+1,t=c0+c1,cut=lo+(r*c0)/t; if(!sym)hi=cut-1;else lo=cut; for(;;){if(hi<0x80000000ULL)out(0);else if(lo>=0x80000000ULL){out(1);lo-=0x80000000ULL;hi-=0x80000000ULL;}else if(lo>=0x40000000ULL&&hi<0xc0000000ULL){++pending;lo-=0x40000000ULL;hi-=0x40000000ULL;}else break;lo<<=1;hi=(hi<<1)|1;lo&=0xffffffffULL;hi&=0xffffffffULL;}}vector<unsigned char> done(){++pending;if(lo<0x40000000ULL)out(0);else out(1);w.finish();return w.o;}};
struct AD{uint64_t lo=0,hi=0xffffffffULL,val=0; BitReader r; AD(const vector<unsigned char>&x):r(x){for(int i=0;i<32;i++)val=(val<<1)|r.bit();}int dec(uint32_t c0,uint32_t c1){uint64_t rg=hi-lo+1,t=c0+c1;uint64_t scaled=((val-lo+1)*t-1)/rg;int sym=scaled>=c0;uint64_t cut=lo+(rg*c0)/t;if(!sym)hi=cut-1;else lo=cut;for(;;){if(hi<0x80000000ULL){}else if(lo>=0x80000000ULL){val-=0x80000000ULL;lo-=0x80000000ULL;hi-=0x80000000ULL;}else if(lo>=0x40000000ULL&&hi<0xc0000000ULL){val-=0x40000000ULL;lo-=0x40000000ULL;hi-=0x40000000ULL;}else break;lo=(lo<<1)&0xffffffffULL;hi=((hi<<1)|1)&0xffffffffULL;val=((val<<1)&0xffffffffULL)|r.bit();}return sym;}};
struct Model{vector<uint16_t>a,b;Model(size_t n):a(n,1),b(n,1){} void upd(size_t k,int s){if(s)b[k]++;else a[k]++;if((uint32_t)a[k]+b[k]>=4096){a[k]=(a[k]+1)>>1;b[k]=(b[k]+1)>>1;if(!a[k])a[k]=1;if(!b[k])b[k]=1;}} int enc(AE&c,size_t k,int s){c.enc(s,a[k],b[k]);upd(k,s);return s;} int dec(AD&c,size_t k){int s=c.dec(a[k],b[k]);upd(k,s);return s;}};
static inline int rcat(int x){if(x==0)return 0;if(x==1)return 1;if(x==-1)return 2;if(x>=2&&x<=3)return 3;if(x<=-2&&x>=-3)return 4;if(x>3)return 5;return 6;}
static inline size_t ctxid(int plane,int gx,int gy,int gt,int rx,int ry){return plane+3ULL*(gx+7ULL*(gy+7ULL*(gt+7ULL*(rx+7ULL*ry))));}
vector<unsigned char> readf(const string&p){ifstream f(p,ios::binary);return vector<unsigned char>((istreambuf_iterator<char>(f)),{});}void writef(const string&p,const vector<unsigned char>&d){ofstream f(p,ios::binary);f.write((char*)d.data(),d.size());}
int main(int ac,char**av){if(ac<8)return 2;string mode=av[1],p1=av[2],p2=av[3],p3=av[4];int W=stoi(av[5]),H=stoi(av[6]),F=stoi(av[7]);auto B=readf(p2);size_t fs=(size_t)W*H*3/2,N=fs*F;if(B.size()!=N)return 3;const size_t NC=3ULL*7*7*7*7*7;Model mz(NC),ms(NC),mm(NC*31);vector<int16_t> R(N,0);int pw[3]={W,W/2,W/2},ph[3]={H,H/2,H/2};size_t po[3]={0,(size_t)W*H,(size_t)W*H+(size_t)W*H/4};
if(mode=="e"){auto O=readf(p1);if(O.size()!=N)return 4;AE coder;long long nz=0;int mx=0;for(int f=0;f<F;f++)for(int p=0;p<3;p++)for(int y=0;y<ph[p];y++)for(int x=0;x<pw[p];x++){size_t q=(size_t)f*fs+po[p]+(size_t)y*pw[p]+x;int bv=B[q];int bl=x?B[q-1]:bv,bt=y?B[q-pw[p]]:bv,bvprev=f?B[q-fs]:bv;int gx=rcat(bv-bl),gy=rcat(bv-bt),gt=rcat(bv-bvprev);int tl=(y?(x?B[q-pw[p]-1]:B[q-pw[p]]):(x?B[q-1]:bv));int pr=bl+bt-tl;pr=max(min(pr,max(bl,bt)),min(bl,bt));int sp=rcat(bv-pr);int rl=x?R[q-1]:0,rt=y?R[q-pw[p]]:0;size_t c=ctxid(p,gx,gy,gt,rcat(rl),rcat(rt));size_t cs=ctxid(p,gx,gy,sp,rcat(rl),rcat(rt));int d=(int)O[q]-bv;R[q]=d;int non=d!=0;mz.enc(coder,c,non);if(non){nz++;mx=max(mx,abs(d));ms.enc(coder,cs,d>0);int m=abs(d);bool stopped=false;for(int th=1;th<=31;th++){int more=m>th;mm.enc(coder,(size_t)(th-1)*NC+c,more);if(!more){stopped=true;break;}}if(!stopped){int ex=m-32;for(int b=7;b>=0;b--)coder.enc((ex>>b)&1,1,1);}}}auto bits=coder.done();writef(p3,bits);cerr<<"events="<<N<<" nz="<<nz<<" max="<<mx<<" bytes="<<bits.size()<<"\n";}
else if(mode=="d"){auto bits=readf(p1);AD coder(bits);vector<unsigned char> O(N);for(int f=0;f<F;f++)for(int p=0;p<3;p++)for(int y=0;y<ph[p];y++)for(int x=0;x<pw[p];x++){size_t q=(size_t)f*fs+po[p]+(size_t)y*pw[p]+x;int bv=B[q];int bl=x?B[q-1]:bv,bt=y?B[q-pw[p]]:bv,bvprev=f?B[q-fs]:bv;int gx=rcat(bv-bl),gy=rcat(bv-bt),gt=rcat(bv-bvprev);int tl=(y?(x?B[q-pw[p]-1]:B[q-pw[p]]):(x?B[q-1]:bv));int pr=bl+bt-tl;pr=max(min(pr,max(bl,bt)),min(bl,bt));int sp=rcat(bv-pr);int rl=x?R[q-1]:0,rt=y?R[q-pw[p]]:0;size_t c=ctxid(p,gx,gy,gt,rcat(rl),rcat(rt));size_t cs=ctxid(p,gx,gy,sp,rcat(rl),rcat(rt));int non=mz.dec(coder,c),d=0;if(non){int pos=ms.dec(coder,cs);int m=0;bool stop=false;for(int th=1;th<=31;th++){int more=mm.dec(coder,(size_t)(th-1)*NC+c);if(!more){m=th;stop=true;break;}}if(!stop){int ex=0;for(int b=7;b>=0;b--)ex=(ex<<1)|coder.dec(1,1);m=32+ex;}d=pos?m:-m;}R[q]=d;int v=bv+d;if(v<0||v>255)return 6;O[q]=v;}writef(p3,O);}else return 2;}
