from pathlib import Path
q=Path('hpez-src/include/QoZ/quantizer/IntegerQuantizer.hpp')
s=q.read_text()
# Track reconstructed innovation r = xhat - raw predictor. Statistics do not alter codec behavior.
s=s.replace('#include <vector>', '#include <vector>\n#include <cstdio>\n#include <cmath>',1)
# Update after successful overwrite in both overloads.
s=s.replace('data = decompressed_data;\n                    return quant_index_shifted;', 'data = decompressed_data;\n                    residual_stat_update((double)(decompressed_data - pred));\n                    return quant_index_shifted;',1)
s=s.replace('dest = decompressed_data;\n                    return quant_index_shifted;', 'dest = decompressed_data;\n                    residual_stat_update((double)(decompressed_data - pred));\n                    return quant_index_shifted;',1)
# Break correlation chain on unpredictable samples, but do not change codec output.
s=s.replace('''if (fabs(decompressed_data - data) > this->error_bound) {\n                    if(save_unpred)\n                        unpred.push_back(data);\n                    return 0;''','''if (fabs(decompressed_data - data) > this->error_bound) {\n                    if(save_unpred) unpred.push_back(data);\n                    residual_stat_reset_line();\n                    stat_unpred++;\n                    return 0;''',1)
s=s.replace('''} else {\n                if(save_unpred)\n                    unpred.push_back(data);\n                return 0;\n            }\n        }\n\n        int quantize_and_overwrite(T ori''','''} else {\n                if(save_unpred) unpred.push_back(data);\n                residual_stat_reset_line(); stat_unpred++;\n                return 0;\n            }\n        }\n\n        int quantize_and_overwrite(T ori''',1)
s=s.replace('''if (fabs(decompressed_data - ori) > this->error_bound) {\n                    if(save_unpred)\n                        unpred.push_back(ori);\n                    dest = ori;\n                    return 0;''','''if (fabs(decompressed_data - ori) > this->error_bound) {\n                    if(save_unpred) unpred.push_back(ori);\n                    dest = ori; residual_stat_reset_line(); stat_unpred++;\n                    return 0;''',1)
s=s.replace('''} else {\n                if(save_unpred)\n                    unpred.push_back(ori);\n                dest = ori;\n                return 0;\n            }\n        }''','''} else {\n                if(save_unpred) unpred.push_back(ori);\n                dest = ori; residual_stat_reset_line(); stat_unpred++;\n                return 0;\n            }\n        }''',1)
# Public line-boundary hook; used only for diagnostics.
s=s.replace('void clear() {\n            unpred.clear();\n            index = 0;\n        }', '''void clear() { unpred.clear(); index = 0; residual_stat_clear(); }\n\n        void residual_stat_new_line() { residual_stat_reset_line(); stat_lines++; }''',1)
# Print correlations after compression. postcompress_data is otherwise empty.
s=s.replace('''virtual void postcompress_data() {\n        }''','''virtual void postcompress_data() {\n            double mean = stat_n ? stat_sum/stat_n : 0.0;\n            double var = stat_n ? stat_sum2/stat_n - mean*mean : 0.0;\n            double c1 = stat_l1_n ? stat_l1_prod/stat_l1_n - (stat_l1_a/stat_l1_n)*(stat_l1_b/stat_l1_n) : 0.0;\n            double v1a = stat_l1_n ? stat_l1_a2/stat_l1_n - std::pow(stat_l1_a/stat_l1_n,2) : 0.0;\n            double v1b = stat_l1_n ? stat_l1_b2/stat_l1_n - std::pow(stat_l1_b/stat_l1_n,2) : 0.0;\n            double rho1 = (v1a>0 && v1b>0) ? c1/std::sqrt(v1a*v1b) : 0.0;\n            double c2 = stat_l2_n ? stat_l2_prod/stat_l2_n - (stat_l2_a/stat_l2_n)*(stat_l2_b/stat_l2_n) : 0.0;\n            double v2a = stat_l2_n ? stat_l2_a2/stat_l2_n - std::pow(stat_l2_a/stat_l2_n,2) : 0.0;\n            double v2b = stat_l2_n ? stat_l2_b2/stat_l2_n - std::pow(stat_l2_b/stat_l2_n,2) : 0.0;\n            double rho2 = (v2a>0 && v2b>0) ? c2/std::sqrt(v2a*v2b) : 0.0;\n            std::fprintf(stderr,"RESIDSTAT n=%llu lines=%llu unpred=%llu mean=%.12g std=%.12g rho1=%.12g rho2=%.12g l1n=%llu l2n=%llu\\n",\n                stat_n,stat_lines,stat_unpred,mean,var>0?std::sqrt(var):0.0,rho1,rho2,stat_l1_n,stat_l2_n);\n        }''',1)
# Insert private state + methods before unpred vector.
needle='''    private:\n        std::vector<T> unpred;'''
insert='''    private:\n        unsigned long long stat_n=0,stat_lines=0,stat_unpred=0,stat_l1_n=0,stat_l2_n=0;\n        double stat_sum=0,stat_sum2=0;\n        double stat_l1_prod=0,stat_l1_a=0,stat_l1_b=0,stat_l1_a2=0,stat_l1_b2=0;\n        double stat_l2_prod=0,stat_l2_a=0,stat_l2_b=0,stat_l2_a2=0,stat_l2_b2=0;\n        double stat_prev1=0,stat_prev2=0; int stat_hist=0;\n        void residual_stat_reset_line(){ stat_hist=0; stat_prev1=stat_prev2=0; }\n        void residual_stat_clear(){ stat_n=stat_lines=stat_unpred=stat_l1_n=stat_l2_n=0; stat_sum=stat_sum2=0; stat_l1_prod=stat_l1_a=stat_l1_b=stat_l1_a2=stat_l1_b2=0; stat_l2_prod=stat_l2_a=stat_l2_b=stat_l2_a2=stat_l2_b2=0; residual_stat_reset_line(); }\n        void residual_stat_update(double r){\n            stat_n++;stat_sum+=r;stat_sum2+=r*r;\n            if(stat_hist>=1){stat_l1_n++;stat_l1_prod+=r*stat_prev1;stat_l1_a+=r;stat_l1_b+=stat_prev1;stat_l1_a2+=r*r;stat_l1_b2+=stat_prev1*stat_prev1;}\n            if(stat_hist>=2){stat_l2_n++;stat_l2_prod+=r*stat_prev2;stat_l2_a+=r;stat_l2_b+=stat_prev2;stat_l2_a2+=r*r;stat_l2_b2+=stat_prev2*stat_prev2;}\n            stat_prev2=stat_prev1;stat_prev1=r;if(stat_hist<2)stat_hist++;\n        }\n        std::vector<T> unpred;'''
if needle not in s: raise SystemExit('private needle missing')
s=s.replace(needle,insert,1)
q.write_text(s)

p=Path('hpez-src/include/QoZ/compressor/SZInterpolationCompressor.hpp')
t=p.read_text()
needle='''        double block_interpolation_1d(T *data, size_t begin, size_t end, size_t stride,const std::string &interp_func,const PredictorBehavior pb,const QoZ::Interp_Meta &meta,int tuning=0) {\n            size_t n = (end - begin) / stride + 1;'''
repl='''        double block_interpolation_1d(T *data, size_t begin, size_t end, size_t stride,const std::string &interp_func,const PredictorBehavior pb,const QoZ::Interp_Meta &meta,int tuning=0) {\n            quantizer.residual_stat_new_line();\n            size_t n = (end - begin) / stride + 1;'''
if needle not in t: raise SystemExit('block line needle missing')
t=t.replace(needle,repl,1)
p.write_text(t)
print('instrumented')
