#include <bits/stdc++.h>
using namespace std;
struct BitWriter{ vector<unsigned char> o; unsigned cur=0,n=0; void bit(int b){cur=(cur<<1)|(b&1); if(++n==8){o.push_back(cur);cur=n=0;}} void finish(){if(n){cur<<=(8-n);o.push_back(cur);cur=n=0;}}};
struct BitReader{ const vector<unsigned char>& a; size_t p=0; int n=0; unsigned cur=0; BitReader(const vector<unsigned char>&x):a(x){} int bit(){if(!n){cur=p<a.size()?a[p++]:0;n=8;} int b=(cur>>7)&1;cur<<=1;--n;return b;}};
struct AE{uint64_t lo=0,hi=0xffffffffULL;unsigned pending=0;BitWriter w;void out(int b){w.bit(b);while(pending){w.bit(!b);--pending;}}void enc(int sym,uint32_t c0,uint32_t c1){uint64_t r=hi-lo+1,t=c0+c1,cut=lo+(r*c0)/t;if(!sym)hi=cut-1;else lo=cut;for(;;){if(hi<0x80000000ULL)out(0);else if(lo>=0x80000000ULL){out(1);lo-=0x80000000ULL;hi-=0x80000000ULL;}else if(lo>=0x40000000ULL&&hi<0xc0000000ULL){++pending;lo-=0x40000000ULL;hi-=0x40000000ULL;}else break;lo<<=1;hi=(hi<<1)|1;lo&=0xffffffffULL;hi&=0xffffffffULL;}}vector<unsigned char> done(){++pending;if(lo<0x40000000ULL)out(0);else out(1);w.finish();return w.o;}};
struct AD{uint64_t lo=0,hi=0xffffffffULL,val=0;BitReader r;AD(const vector<unsigned char>&x):r(x){for(int i=0;i<32;i++)val=(val<<1)|r.bit();}int dec(uint32_t c0,uint32_t c1){uint64_t rg=hi-lo+1,t=c0+c1,scaled=((val-lo+1)*t-1)/rg;int sym=scaled>=c0;uint64_t cut=lo+(rg*c0)/t;if(!sym)hi=cut-1;else lo=cut;for(;;){if(hi<0x80000000ULL){}else if(lo>=0x80000000ULL){val-=0x80000000ULL;lo-=0x80000000ULL;hi-=0x80000000ULL;}else if(lo>=0x40000000ULL&&hi<0xc0000000ULL){val-=0x40000000ULL;lo-=0x40000000ULL;hi-=0x40000000ULL;}else break;lo=(lo<<1)&0xffffffffULL;hi=((hi<<1)|1)&0xffffffffULL;val=((val<<1)&0xffffffffULL)|r.bit();}return sym;}};
struct LatticeModel{vector<uint16_t>a,b,pa,pb,ga,gb,xa,xb;unsigned lf,lp,lx;LatticeModel(size_t n,size_t pn,size_t gn,size_t xn,unsigned LF,unsigned LP,unsigned LX):a(n,0),b(n,0),pa(pn,0),pb(pn,0),ga(gn,1),gb(gn,1),xa(xn,1),xb(xn,1),lf(LF),lp(LP),lx(LX){}void up(vector<uint16_t>&x,vector<uint16_t>&y,size_t k,int s){if(s)y[k]++;else x[k]++;if((uint32_t)x[k]+y[k]>=4096){x[k]=(x[k]+1)>>1;y[k]=(y[k]+1)>>1;if(!x[k]&&!y[k]){x[k]=1;y[k]=1;}}}pair<uint32_t,uint32_t> peff(size_t j,size_t g){uint32_t gt=ga[g]+gb[g];uint32_t aa=pa[j]+max(1u,(lp*(uint32_t)ga[g]+gt/2)/gt);uint32_t bb=pb[j]+max(1u,(lp*(uint32_t)gb[g]+gt/2)/gt);return {aa,bb};}pair<uint32_t,uint32_t> eff(size_t k,size_t j,size_t g,size_t x){auto p=peff(j,g);uint32_t pt=p.first+p.second,xt=xa[x]+xb[x];uint32_t aa=a[k]+max(1u,(lf*p.first+pt/2)/pt)+max(1u,(lx*(uint32_t)xa[x]+xt/2)/xt);uint32_t bb=b[k]+max(1u,(lf*p.second+pt/2)/pt)+max(1u,(lx*(uint32_t)xb[x]+xt/2)/xt);return {aa,bb};}int enc(AE&c,size_t k,size_t j,size_t g,size_t x,int s){auto e=eff(k,j,g,x);c.enc(s,e.first,e.second);up(a,b,k,s);up(pa,pb,j,s);up(ga,gb,g,s);up(xa,xb,x,s);return s;}int dec(AD&c,size_t k,size_t j,size_t g,size_t x){auto e=eff(k,j,g,x);int s=c.dec(e.first,e.second);up(a,b,k,s);up(pa,pb,j,s);up(ga,gb,g,s);up(xa,xb,x,s);return s;}};
static inline int rcat(int x){if(x==0)return 0;if(x==1)return 1;if(x==-1)return 2;if(x>=2&&x<=3)return 3;if(x<=-2&&x>=-3)return 4;if(x>3)return 5;return 6;}
static inline size_t ctxid(int p,int gx,int gy,int gt,int rx,int ry){return p+3ULL*(gx+7ULL*(gy+7ULL*(gt+7ULL*(rx+7ULL*ry))));}
static inline size_t ctxid4(int p,int gx,int gy,int gt,int rx){return p+3ULL*(gx+7ULL*(gy+7ULL*(gt+7ULL*rx)));}
static inline size_t ctxid6(int p,int gx,int gy,int gt,int rx,int ry,int rp){return p+3ULL*(gx+7ULL*(gy+7ULL*(gt+7ULL*(rx+7ULL*(ry+7ULL*rp)))));}
vector<unsigned char> readf(const string&p){ifstream f(p,ios::binary);return vector<unsigned char>((istreambuf_iterator<char>(f)),{});}void writef(const string&p,const vector<unsigned char>&d){ofstream f(p,ios::binary);f.write((char*)d.data(),d.size());}
int main(int ac,char**av){if(ac<8)return 2;string mode=av[1],p1=av[2],p2=av[3],p3=av[4];int W=stoi(av[5]),H=stoi(av[6]),F=stoi(av[7]);auto B=readf(p2);size_t fs=(size_t)W*H*3/2,N=fs*F;if(B.size()!=N)return 3;const size_t NC=3ULL*7*7*7*7*7*7,NCP=3ULL*7*7*7*7*7,NCGP=3ULL*7*7*7*7,NCZ=NC*8ULL,XP=3ULL*7*7*7,XPZ=XP*8ULL;LatticeModel mz(NCZ,NC,NCP,XPZ,64,32,24),ms(NC,NCP,NCGP,XP,32,4,16),mm(NC*31,NCP*31,NCGP*31,XP*31,16,16,16);vector<int16_t>R(N,0);int pw[3]={W,W/2,W/2},ph[3]={H,H/2,H/2};size_t po[3]={0,(size_t)W*H,(size_t)W*H+(size_t)W*H/4};
if(mode=="e"){auto O=readf(p1);if(O.size()!=N)return 4;AE coder;for(int f=0;f<F;f++)for(int p=0;p<3;p++)for(int y=0;y<ph[p];y++)for(int x=0;x<pw[p];x++){size_t q=(size_t)f*fs+po[p]+(size_t)y*pw[p]+x;int bv=B[q],bl=x?B[q-1]:bv,bt=y?B[q-pw[p]]:bv,bp=f?B[q-fs]:bv,gx=rcat(bv-bl),gy=rcat(bv-bt),gt=rcat(bv-bp);int tl=(y?(x?B[q-pw[p]-1]:B[q-pw[p]]):(x?B[q-1]:bv)),pr=bl+bt-tl;pr=max(min(pr,max(bl,bt)),min(bl,bt));int sp=rcat(bv-pr),rl=x?R[q-1]:0,rt=y?R[q-pw[p]]:0,rp=f?R[q-fs]:0;size_t c=ctxid6(p,gx,gy,gt,rcat(rl),rcat(rt),rcat(rp)),cs=ctxid6(p,gx,gy,sp,rcat(rl),rcat(rt),rcat(rp)),cm=ctxid(p,gx,gy,gt,rcat(rl),rcat(rt)),cms=ctxid(p,gx,gy,sp,rcat(rl),rcat(rt)),cg=ctxid4(p,gx,gy,gt,rcat(rl)),cgs=ctxid4(p,gx,gy,sp,rcat(rl)),xp=p+3ULL*(rcat(rl)+7ULL*(rcat(rt)+7ULL*rcat(rp))),xpz=xp+XP*(bv>>5),cz=c*8ULL+(bv>>5);int d=(int)O[q]-bv;R[q]=d;int non=d!=0;mz.enc(coder,cz,c,cm,xpz,non);if(non){ms.enc(coder,cs,cms,cgs,xp,d>0);int m=abs(d);bool stop=0;for(int th=1;th<=31;th++){int more=m>th;mm.enc(coder,(size_t)(th-1)*NC+c,(size_t)(th-1)*NCP+cm,(size_t)(th-1)*NCGP+cg,(size_t)(th-1)*XP+xp,more);if(!more){stop=1;break;}}if(!stop){int ex=m-32;for(int b=7;b>=0;b--)coder.enc((ex>>b)&1,1,1);}}}writef(p3,coder.done());}
else if(mode=="d"){auto bits=readf(p1);AD coder(bits);vector<unsigned char>O(N);for(int f=0;f<F;f++)for(int p=0;p<3;p++)for(int y=0;y<ph[p];y++)for(int x=0;x<pw[p];x++){size_t q=(size_t)f*fs+po[p]+(size_t)y*pw[p]+x;int bv=B[q],bl=x?B[q-1]:bv,bt=y?B[q-pw[p]]:bv,bp=f?B[q-fs]:bv,gx=rcat(bv-bl),gy=rcat(bv-bt),gt=rcat(bv-bp);int tl=(y?(x?B[q-pw[p]-1]:B[q-pw[p]]):(x?B[q-1]:bv)),pr=bl+bt-tl;pr=max(min(pr,max(bl,bt)),min(bl,bt));int sp=rcat(bv-pr),rl=x?R[q-1]:0,rt=y?R[q-pw[p]]:0,rp=f?R[q-fs]:0;size_t c=ctxid6(p,gx,gy,gt,rcat(rl),rcat(rt),rcat(rp)),cs=ctxid6(p,gx,gy,sp,rcat(rl),rcat(rt),rcat(rp)),cm=ctxid(p,gx,gy,gt,rcat(rl),rcat(rt)),cms=ctxid(p,gx,gy,sp,rcat(rl),rcat(rt)),cg=ctxid4(p,gx,gy,gt,rcat(rl)),cgs=ctxid4(p,gx,gy,sp,rcat(rl)),xp=p+3ULL*(rcat(rl)+7ULL*(rcat(rt)+7ULL*rcat(rp))),xpz=xp+XP*(bv>>5),cz=c*8ULL+(bv>>5);int non=mz.dec(coder,cz,c,cm,xpz),d=0;if(non){int pos=ms.dec(coder,cs,cms,cgs,xp),m=0;bool stop=0;for(int th=1;th<=31;th++){int more=mm.dec(coder,(size_t)(th-1)*NC+c,(size_t)(th-1)*NCP+cm,(size_t)(th-1)*NCGP+cg,(size_t)(th-1)*XP+xp);if(!more){m=th;stop=1;break;}}if(!stop){int ex=0;for(int b=7;b>=0;b--)ex=(ex<<1)|coder.dec(1,1);m=32+ex;}d=pos?m:-m;}R[q]=d;int v=bv+d;if(v<0||v>255)return 6;O[q]=v;}writef(p3,O);}else return 2;}
